### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by farhanwazir** [domProjects/CI-AdminLTE#11]
Everything is working fine but why every time white screen appears when i click on pagination button. It loads via ajax and after clicked screen goes white.

I'm using bootstrap-table for loading data.

**Comment by domProjects** [comment]
sorry for the late reply, I was on vacation !!!

without your code I can not help you. Watch the link http://www.kodingmadesimple.com/2015/04/php-codeigniter-pagination-twitter-bootstrap-styles.html

I tested it and it works fine.
