### ISSUE TITLE
.gitignore and gitatributes detected as virus by my smadav

### ISSUE THREAD

**Issue by helwieahmad** [domProjects/CI-AdminLTE#12]
hi guys... 
after i extract the zip file. the gitignore and gitattribute have moved to quarantine becauze detected as vbs.trashes.bat virus by smadav antivirus. how i will use this projects? thanks in advance.

**Comment by domProjects** [comment]
sorry for the late reply, I was on vacation !!!
I can confirm that the project does not contain any virus. Your antivirus should misinterpret the contents of files .gitignore and gitatributes
