### ISSUE TITLE
Maximum execution time of 30 seconds exceeded 

### ISSUE THREAD

**Issue by patelakash2308** [domProjects/CI-AdminLTE#16]
when i am try to intall in localhost it display error like below.

Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\CI-AdminLTE-master\system\libraries\Session\drivers\Session_files_driver.php on line 169
A PHP Error was encountered

Severity: Error

Message: Maximum execution time of 30 seconds exceeded

Filename: drivers/Session_files_driver.php

Line Number: 169

Backtrace:

**Comment by TowerX** [comment]
Try changing the "max_execution_time" to something higher than 30, in your php.ini file. If you need help locating the file, let me know.
