### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by gcesario** [domProjects/CI-AdminLTE#4]
Hello there!
I explained how I could install ci_admin_lte?
Thank you very much and best regards

**Comment by gofunbox** [comment]
1.config mysql (file path application/config/database.php)
2.import sql (file path install/sql/ci_adminlte.sql)
3.in application/config/config.php
change $config['base_url'] = 'your Site URL';
change $config['sess_save_path'] = 'ci_sessions';
