### ISSUE TITLE
toggle not work

### ISSUE THREAD

**Issue by FoxMiner** [domProjects/CI-AdminLTE#5]
In menu  Preferences Interfaces you check Transition page to YES 
toggle menus not work correct:

JS Error:
Uncaught Error: Syntax error, unrecognized expression: [href^=#]
fa.error @ jquery.min.js:2
fa.tokenize @ jquery.min.js:2
fa.compile @ jquery.min.js:2
(anonymous function) @ jquery.min.js:2
fa.selectors.filter.PSEUDO @ jquery.min.js:2
wa @ jquery.min.js:2
fa.compile @ jquery.min.js:2
fa.select @ jquery.min.js:2
fa @ jquery.min.js:2
n.event.handlers @ jquery.min.js:3
n.event.dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

**Comment by domProjects** [comment]
Thank you @FoxMiner  for your return. I look at the problem.

**Comment by domProjects** [comment]
problem solved !!! thank you @FoxMiner
