### ISSUE TITLE
The Tabs in Control sidebar Show blank page

### ISSUE THREAD

**Issue by FoxMiner** [domProjects/CI-AdminLTE#6]
Bug:
The Tabs in Control sidebar Not work if you select in Preferences transition page to YES

Suggestion:
I think you should call the language file, the login page in a different way to "auth_lang" . 
login_lang for example, to avoid overwriting the auth Ion update in the future and keep the names of the files unchanged.

thank you very much for your work I will be of great help for my first project.

**Comment by domProjects** [comment]
Good evening and thank you again @FoxMiner 

For error indicated I will correct it. For part control sidebar I will correct that. For the language file authentication I'm any overhaul.

See you soon !!!
