### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by cumez1** [domProjects/CI-AdminLTE#7]
Hello I can support the installation,
or that steps have to follow.

**Comment by FoxMiner** [comment]
You do not have to install anything only download the file and unzip it on your development server.

The file already has all the necessary dependencies and a basic pre-configuration of the environment and the skeleton of the views, controllers and models.

In the first instance you need to configure the environment, modifying the configuration files codeigniter, ION_AUTH.

To use this repo you need to know perfectly Codeigniter, Bootstrap. It is also important to know the ion_auth library.

Here you have the necessary documentation.
-   http://www.codeigniter.com/user_guide/installation/index.html
-   http://benedmunds.com/ion_auth/
-   https://almsaeedstudio.com/themes/AdminLTE/documentation/index.html

**Comment by cumez1** [comment]
Thanks for your support!
;)
